# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.crate_api import CrateApi


class TestCrateApi(unittest.TestCase):
    """CrateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CrateApi()

    def tearDown(self) -> None:
        pass

    def test_file_symbols(self) -> None:
        """Test case for file_symbols

        """
        pass

    def test_get_definition(self) -> None:
        """Test case for get_definition

        """
        pass

    def test_get_references(self) -> None:
        """Test case for get_references

        """
        pass

    def test_workspace_symbols(self) -> None:
        """Test case for workspace_symbols

        """
        pass


if __name__ == '__main__':
    unittest.main()
