# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.custom_reference_response import CustomReferenceResponse

class TestCustomReferenceResponse(unittest.TestCase):
    """CustomReferenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomReferenceResponse:
        """Test CustomReferenceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomReferenceResponse`
        """
        model = CustomReferenceResponse()
        if include_optional:
            return CustomReferenceResponse(
                raw_response = None,
                references = [
                    openapi_client.models.simplified_location.SimplifiedLocation(
                        character = 0, 
                        line = 0, 
                        uri = '', )
                    ]
            )
        else:
            return CustomReferenceResponse(
                raw_response = None,
                references = [
                    openapi_client.models.simplified_location.SimplifiedLocation(
                        character = 0, 
                        line = 0, 
                        uri = '', )
                    ],
        )
        """

    def testCustomReferenceResponse(self):
        """Test CustomReferenceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
