# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.simplified_document_symbol import SimplifiedDocumentSymbol

class TestSimplifiedDocumentSymbol(unittest.TestCase):
    """SimplifiedDocumentSymbol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimplifiedDocumentSymbol:
        """Test SimplifiedDocumentSymbol
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimplifiedDocumentSymbol`
        """
        model = SimplifiedDocumentSymbol()
        if include_optional:
            return SimplifiedDocumentSymbol(
                character = 0,
                kind = '',
                line = 0,
                name = ''
            )
        else:
            return SimplifiedDocumentSymbol(
                character = 0,
                kind = '',
                line = 0,
                name = '',
        )
        """

    def testSimplifiedDocumentSymbol(self):
        """Test SimplifiedDocumentSymbol"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
