# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.supported_lsp import SupportedLSP

class TestSupportedLSP(unittest.TestCase):
    """SupportedLSP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupportedLSP(self):
        """Test SupportedLSP"""
        # inst = SupportedLSP()

if __name__ == '__main__':
    unittest.main()
