# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.custom_goto_definition_response import CustomGotoDefinitionResponse

class TestCustomGotoDefinitionResponse(unittest.TestCase):
    """CustomGotoDefinitionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomGotoDefinitionResponse:
        """Test CustomGotoDefinitionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomGotoDefinitionResponse`
        """
        model = CustomGotoDefinitionResponse()
        if include_optional:
            return CustomGotoDefinitionResponse(
                definitions = [
                    openapi_client.models.simplified_location.SimplifiedLocation(
                        character = 0, 
                        line = 0, 
                        uri = '', )
                    ],
                raw_response = None
            )
        else:
            return CustomGotoDefinitionResponse(
                definitions = [
                    openapi_client.models.simplified_location.SimplifiedLocation(
                        character = 0, 
                        line = 0, 
                        uri = '', )
                    ],
                raw_response = None,
        )
        """

    def testCustomGotoDefinitionResponse(self):
        """Test CustomGotoDefinitionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
