# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lsproxy_sdk.models.references_response import ReferencesResponse

class TestReferencesResponse(unittest.TestCase):
    """ReferencesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReferencesResponse:
        """Test ReferencesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReferencesResponse`
        """
        model = ReferencesResponse()
        if include_optional:
            return ReferencesResponse(
                context = [
                    lsproxy_sdk.models.code_context.CodeContext(
                        range = lsproxy_sdk.models.file_range.FileRange(
                            end = lsproxy_sdk.models.position.Position(
                                character = 5, 
                                line = 10, ), 
                            path = 'src/main.py', 
                            start = lsproxy_sdk.models.position.Position(
                                character = 5, 
                                line = 10, ), ), 
                        source_code = '', )
                    ],
                raw_response = None,
                references = [
                    lsproxy_sdk.models.file_position.FilePosition(
                        path = 'src/main.py', 
                        position = lsproxy_sdk.models.position.Position(
                            character = 5, 
                            line = 10, ), )
                    ]
            )
        else:
            return ReferencesResponse(
                references = [
                    lsproxy_sdk.models.file_position.FilePosition(
                        path = 'src/main.py', 
                        position = lsproxy_sdk.models.position.Position(
                            character = 5, 
                            line = 10, ), )
                    ],
        )
        """

    def testReferencesResponse(self):
        """Test ReferencesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
