# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lsproxy_sdk.models.file_position import FilePosition

class TestFilePosition(unittest.TestCase):
    """FilePosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilePosition:
        """Test FilePosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilePosition`
        """
        model = FilePosition()
        if include_optional:
            return FilePosition(
                path = 'src/main.py',
                position = lsproxy_sdk.models.position.Position(
                    character = 5, 
                    line = 10, )
            )
        else:
            return FilePosition(
                path = 'src/main.py',
                position = lsproxy_sdk.models.position.Position(
                    character = 5, 
                    line = 10, ),
        )
        """

    def testFilePosition(self):
        """Test FilePosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
