# coding: utf-8

"""
    lsproxy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.custom_document_symbol_response import CustomDocumentSymbolResponse

class TestCustomDocumentSymbolResponse(unittest.TestCase):
    """CustomDocumentSymbolResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomDocumentSymbolResponse:
        """Test CustomDocumentSymbolResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomDocumentSymbolResponse`
        """
        model = CustomDocumentSymbolResponse()
        if include_optional:
            return CustomDocumentSymbolResponse(
                document_symbols = [
                    openapi_client.models.simplified_document_symbol.SimplifiedDocumentSymbol(
                        character = 0, 
                        kind = '', 
                        line = 0, 
                        name = '', )
                    ],
                raw_response = None
            )
        else:
            return CustomDocumentSymbolResponse(
                document_symbols = [
                    openapi_client.models.simplified_document_symbol.SimplifiedDocumentSymbol(
                        character = 0, 
                        kind = '', 
                        line = 0, 
                        name = '', )
                    ],
                raw_response = None,
        )
        """

    def testCustomDocumentSymbolResponse(self):
        """Test CustomDocumentSymbolResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
